name: volleyapp
description: your volley scoreboard app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0
  provider: ^6.0.0 
  intl: ^0.17.0
  path_provider: ^2.1.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ball.png

  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ball.png"